# Generated by Django 4.2.7 on 2023-11-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voom_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='delivery_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
