# Generated by Django 4.2.7 on 2023-11-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voom_api', '0002_alter_seller_rating_alter_transactions_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
